@echo off
setlocal
echo [1/3] Closing any leftover automation Chrome...
powershell -NoProfile -Command "Get-CimInstance Win32_Process -Filter \"Name='chrome.exe'\" | Where-Object { $_.CommandLine -match 'chrome_profile_real|remote-debugging-port=9222' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }"
echo [2/3] Waiting for port 9222 to be free...
powershell -NoProfile -Command "$deadline = (Get-Date).AddSeconds(20); while ((Get-NetTCPConnection -LocalPort 9222 -ErrorAction SilentlyContinue) -and (Get-Date) -lt $deadline) { Start-Sleep -Milliseconds 500 }; if (Get-NetTCPConnection -LocalPort 9222 -ErrorAction SilentlyContinue) { Write-Output 'PORT_STILL_IN_USE' } else { Write-Output 'PORT_FREE' }"
echo [3/3] Starting automation Chrome with remote debugging...
start "" "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="%~dp0chrome_profile_real"
echo Automation Chrome started. Port 9222 should now be listening.
